apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misskey.fullname" . }}
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "misskey.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "misskey.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: misskey
          image: {{ .Values.image }}
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ include "misskey.fullname" . }}-configuration
              mountPath: /misskey/.config
              readOnly: true
          ports:
            - containerPort: 3000
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "example-misskey-user"
            - name: POSTGRES_PASSWORD
              value: "example-misskey-pass"
            - name: POSTGRES_DB
              value: "misskey"
          ports:
            - containerPort: 5432
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          env:
            - name: DFLY_version_check
              value: false
            - name: DFLY_tcp_backlog
              value: 2048
            - name: DFLY_lock_on_hashtags
              value: true
            - name: DFLY_pipeline_squash
              value: 0
            - name: DFLY_multi_exec_squash
              value: false
            - name: DFLY_conn_io_threads
              value: 4
            - name: DFLY_epoll_file_threads
              value: 4
            - name: DFLY_proactor_threads
              value: 4
          ports:
            - containerPort: 6379
      volumes:
        - name: {{ include "misskey.fullname" . }}-configuration
          configMap:
            name: {{ include "misskey.fullname" . }}-configuration
